# ========================================
# POPULAR FORMATS
# ========================================

[[format]]
extension = "mp3"
name = "MP3 (MPEG Audio Layer 3)"
category = "popular"
codec = "libmp3lame"
container = ""
stability = "stable"
description = "Universal lossy audio format with excellent compatibility"
typical_use = "Music, podcasts, general audio"
lossy = true
bitrate_range = [64, 320]
recommended_bitrate = 192
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000]
recommended_sample_rate = 44100
channels_support = [1, 2]
special_params = []

[[format]]
extension = "aac"
name = "AAC (Advanced Audio Coding)"
category = "popular"
codec = "aac"
container = ""
stability = "stable"
description = "Modern lossy format, better quality than MP3 at same bitrate"
typical_use = "Streaming, iTunes, modern devices"
lossy = true
bitrate_range = [64, 512]
recommended_bitrate = 256
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]
recommended_sample_rate = 48000
channels_support = [1, 2, 6, 8]
special_params = []

[[format]]
extension = "m4a"
name = "M4A (MPEG-4 Audio)"
category = "popular"
codec = "aac"
container = "mp4"
stability = "stable"
description = "AAC audio in MP4 container, Apple standard"
typical_use = "Apple devices, iTunes Store"
lossy = true
bitrate_range = [64, 512]
recommended_bitrate = 256
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]
recommended_sample_rate = 48000
channels_support = [1, 2, 6, 8]
special_params = ["-f", "mp4"]

[[format]]
extension = "flac"
name = "FLAC (Free Lossless Audio Codec)"
category = "popular"
codec = "flac"
container = ""
stability = "stable"
description = "Lossless compression, perfect audio quality"
typical_use = "Music archiving, audiophile collections"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = ["-compression_level", "8"]

[[format]]
extension = "wav"
name = "WAV (Waveform Audio File)"
category = "popular"
codec = "pcm_s16le"
container = ""
stability = "stable"
description = "Uncompressed PCM audio, CD quality"
typical_use = "Professional audio editing, CD authoring"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = []

[[format]]
extension = "ogg"
name = "OGG Vorbis"
category = "popular"
codec = "libvorbis"
container = "ogg"
stability = "stable"
description = "Open-source lossy format, alternative to MP3"
typical_use = "Gaming, open-source projects"
lossy = true
bitrate_range = [64, 500]
recommended_bitrate = 192
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = ["-q:a", "6"]

[[format]]
extension = "opus"
name = "Opus"
category = "popular"
codec = "libopus"
container = "ogg"
stability = "stable"
description = "Modern universal codec, excellent for speech and music"
typical_use = "VoIP, streaming, low-latency audio"
lossy = true
bitrate_range = [6, 510]
recommended_bitrate = 128
sample_rates = [8000, 12000, 16000, 24000, 48000]
recommended_sample_rate = 48000
channels_support = [1, 2, 6, 8]
special_params = []

# ========================================
# STANDARD FORMATS
# ========================================

[[format]]
extension = "alac"
name = "ALAC (Apple Lossless)"
category = "standard"
codec = "alac"
container = "mp4"
stability = "stable"
description = "Apple's lossless codec"
typical_use = "Apple ecosystem, iTunes"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = ["-f", "mp4"]

[[format]]
extension = "wma"
name = "WMA (Windows Media Audio)"
category = "standard"
codec = "wmav2"
container = "asf"
stability = "requiressetup"
description = "Microsoft's audio format (stereo only, for multichannel use WMA Pro)"
typical_use = "Windows applications, legacy systems"
lossy = true
bitrate_range = [64, 320]
recommended_bitrate = 192
sample_rates = [8000, 16000, 22050, 32000, 44100, 48000]
recommended_sample_rate = 44100
channels_support = [1, 2]
special_params = ["-strict", "-2"]

[[format]]
extension = "aiff"
name = "AIFF (Audio Interchange File Format)"
category = "standard"
codec = "pcm_s16be"
container = ""
stability = "stable"
description = "Apple's uncompressed audio format"
typical_use = "Mac audio production"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = []

[[format]]
extension = "wv"
name = "WavPack"
category = "standard"
codec = "wavpack"
container = ""
stability = "stable"
description = "Hybrid lossless/lossy compression"
typical_use = "Flexible audio archiving"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000, 192000]
recommended_sample_rate = 44100
channels_support = [1, 2, 6, 8]
special_params = []

# ========================================
# SPECIALIZED FORMATS
# ========================================

[[format]]
extension = "tta"
name = "TTA (True Audio)"
category = "specialized"
codec = "tta"
container = ""
stability = "stable"
description = "Real-time lossless codec"
typical_use = "Lossless archiving"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]
recommended_sample_rate = 44100
channels_support = [1, 2]
special_params = []

[[format]]
extension = "ac3"
name = "AC3 (Dolby Digital)"
category = "specialized"
codec = "ac3"
container = ""
stability = "stable"
description = "Multichannel audio for home theater"
typical_use = "DVD, Blu-ray, home cinema"
lossy = true
bitrate_range = [96, 640]
recommended_bitrate = 448
sample_rates = [32000, 44100, 48000]
recommended_sample_rate = 48000
channels_support = [1, 2, 6]
special_params = []

[[format]]
extension = "dts"
name = "DTS (Digital Theater Systems)"
category = "specialized"
codec = "dca"
container = ""
stability = "requiressetup"
description = "High-quality multichannel audio (FFmpeg encoder supports up to 5.1 @ 48 kHz)"
typical_use = "Blu-ray, home theater"
lossy = true
bitrate_range = [754, 1509]
recommended_bitrate = 1509
sample_rates = [8000, 11025, 12000, 16000, 22050, 24000, 32000, 44100, 48000]
recommended_sample_rate = 48000
channels_support = [1, 2, 4, 6]
special_params = ["-strict", "-2"]

[[format]]
extension = "amr"
name = "AMR (Adaptive Multi-Rate)"
category = "specialized"
codec = "libopencore_amrnb"
container = ""
stability = "requiressetup"
description = "Optimized for speech, mobile telephony (4.75-12.2 kbps)"
typical_use = "Voice recordings, GSM"
lossy = true
bitrate_range = [5, 13]
recommended_bitrate = 12
sample_rates = [8000]
recommended_sample_rate = 8000
channels_support = [1]
special_params = ["-ar", "8000"]

# ========================================
# LEGACY FORMATS
# ========================================

[[format]]
extension = "au"
name = "AU (Sun Audio)"
category = "legacy"
codec = "pcm_s16be"
container = ""
stability = "stable"
description = "Unix/Sun audio format"
typical_use = "Legacy Unix systems"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 44100]
recommended_sample_rate = 8000
channels_support = [1, 2]
special_params = []

[[format]]
extension = "ra"
name = "RealAudio"
category = "legacy"
codec = "real_144"
container = "rm"
stability = "experimental"
description = "Legacy streaming audio (mono 8 kHz only)"
typical_use = "Old internet radio archives"
lossy = true
bitrate_range = [8, 14]
recommended_bitrate = 14
sample_rates = [8000]
recommended_sample_rate = 8000
channels_support = [1]
special_params = ["-strict", "-2"]

[[format]]
extension = "shn"
name = "Shorten"
category = "legacy"
codec = "shorten"
container = ""
stability = "problematic"
description = "Old lossless compression"
typical_use = "Legacy audio archives"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [44100]
recommended_sample_rate = 44100
channels_support = [2]
special_params = []

# ========================================
# EXOTIC FORMATS
# ========================================

[[format]]
extension = "mka"
name = "MKA (Matroska Audio)"
category = "exotic"
codec = "copy"
container = "matroska"
stability = "stable"
description = "Matroska container for audio"
typical_use = "Multi-track audio projects"
lossy = false
bitrate_range = []
recommended_bitrate = 0
sample_rates = [8000, 16000, 22050, 24000, 32000, 44100, 48000, 96000]
recommended_sample_rate = 48000
channels_support = [1, 2, 6, 8]
special_params = []

[[format]]
extension = "spx"
name = "Speex"
category = "exotic"
codec = "libspeex"
container = "ogg"
stability = "requiressetup"
description = "Optimized for speech compression"
typical_use = "VoIP, voice chat"
lossy = true
bitrate_range = [2, 44]
recommended_bitrate = 24
sample_rates = [8000, 16000, 32000]
recommended_sample_rate = 16000
channels_support = [1, 2]
special_params = ["-ar", "16000"]